apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 8000 # Container port
  type: LoadBalancer # Expose the service externally using a load balancer


